/**
 * @api {get} /webservice/index.php/app2/index All Issues
 * @apiName All Issues
 * @apiVersion 0.1.0
 * @apiGroup Mobile Application API
 * @apiDescription API will return all the Issues for the specific App-ID & Journal
 *
 * @apiParam {String} appid Application ID generated by Jat 4.0.
 * @apiParam {Number} jid Journal ID. 
 * @apiParam {String} urlcode Must equal "issues".



 * @apiSuccess {Date} date Server current timestamp.
 * @apiSuccess {Number} STATUS Status for the response.
 * @apiSuccess {String} MESSAGE Status message for the response.
 * @apiSuccess {Object[]} ISSUES Array of ISSUE Objects.
 * @apiSuccess {Object[]} MEDIA_TYPE Array of MEDIA_TYPE Objects.
 * @apiSuccess {Number} aip_badge Article in Press badge number. 
 
 * @apiSuccess (ISSUE Object){Date} date Last time data got updated.
 * @apiSuccess (ISSUE Object){String} MESSAGE Status message for the response.
 * @apiSuccess (ISSUE Object){Number} STATUS Status for the response.
 * @apiSuccess (ISSUE Object){Number} issue_id Unique Issue id for the Journal.
 * @apiSuccess (ISSUE Object){String} issue_number Issue number for the Journal.
 * @apiSuccess (ISSUE Object){String} issue_name Issue Name.
 * @apiSuccess (ISSUE Object){Number} volume Volume number of the Issue.
 * @apiSuccess (ISSUE Object){String} editors Editors of the Issue.
 * @apiSuccess (ISSUE Object){String} page_range Page Range of the Issue.
 * @apiSuccess (ISSUE Object){Date}   last_modified  Last modified time.
 * @apiSuccess (ISSUE Object){String} issue_title Issue Title.
 * @apiSuccess (ISSUE Object){String} special_editors Special Editors of the Issue.
 * @apiSuccess (ISSUE Object){String} special_Issue Special Issue linked with the Issue.
 * @apiSuccess (ISSUE Object){String} Video Video URL for the Issue.
 * @apiSuccess (ISSUE Object){String} Cover_Image Cover Image path for the Issue.
 * @apiSuccess (ISSUE Object){String} Product_ID Product ID for the Issue.
 * @apiSuccess (ISSUE Object){String} Price Price for the Issue.       
 * @apiSuccess (ISSUE Object){String} Issue_PII PII number for the Issue.   


 * @apiSuccess (MEDIA_TYPE Object){Number} media_type_id Defines the Media Type.        
 * @apiSuccess (MEDIA_TYPE Object){String} media_type Defines the Media name.  
         	
 * @apiSuccessExample Success-Response:
 *{
 *   "date": "2013-08-19 12:35:16",
 *   "STATUS": "1",
 *   "MESSAGE": "Data Found",
 *   "ISSUES": [
 *       {
 *           "issue_id": "1",
 *           "issue_number": "6, Supplement",
 *           "issue_name": "Endometriosis: ancient disease,ancient treatments",
 *           "volume": "98",
 *           "editors": "Camran Nezhat MD",
 *           "date_of_release": "2012-12-01",
 *           "page_range": "A1-A2, S1-S62",
 *           "last_modified": "2013-08-06 14:55:00",
 *           "issue_title": "Endometriosis: ancient disease,ancient treatments",
 *           "special_editors": "Camran Nezhat MD",
 *           "special_Issue": "\u0001",
 *           "Video": "\u0000",
 *           "Cover_Image": "1.jpg",
 *           "Product_ID": "com.elsevier.gmr.jat.newsstand.fns.singleissue.S0015028212X00025",
 *           "Price": "$31.99",
 *           "Issue_PII": "S0161642013X00089"
 *       }
 *   ],
 *   "MEDIA_TYPE": [
 *       {
 *           "media_type_id": "1",
 *           "media_type": "Video"
 *       },
 *       {
 *           "media_type_id": "2",
 *           "media_type": "Audio"
 *       },
 *       {
 *           "media_type_id": "3",
 *           "media_type": "Document"
 *       },
 *       {
 *           "media_type_id": "4",
 *           "media_type": "Presentation"
 *       },
 *       {
 *           "media_type_id": "5",
 *           "media_type": "Spreadsheet"
 *       },
 *       {
 *           "media_type_id": "6",
 *           "media_type": "PDF"
 *       },
 *       {
 *           "media_type_id": "7",
 *           "media_type": "Image"
 *       },
 *       {
 *           "media_type_id": "8",
 *           "media_type": "Table"
 *       }
 *   ],
 *   "aip_badge": 0
 *}


 
 * @apiError {Date} date Server current timestamp.
 * @apiError {String} MESSAGE Error Message.
 * @apiError {Number} STATUS Error Status Code.

 *
 * @apiErrorExample Error-Response:
 * {
 *	 "date": "2013-08-19 11:39:00",
 *	 "MESSAGE": "No Data Found. Journal id is either empty or wrong.",
 *	 "STATUS": "0"
 * }   
 */