/**
 * @api {get} webservice/index.php/app2/index All Journals
 * @apiName All Journals
 * @apiVersion 0.1.0
 * @apiGroup Mobile Application API
 * @apiDescription API will return all the Journals for the specific App-ID
 *
 * @apiParam {Number} appid Application ID generated by Jat 4.0.
 *
 * @apiSuccess {Date} Server current timestamp.
 * @apiSuccess {Number} STATUS Status for the response.
 * @apiSuccess {String} MESSAGE Status message for the response.
 * @apiSuccess {Object} METADATA METADATA Object.



 * @apiSuccess (METADATA Object){Number} App_ID Application ID.
 * @apiSuccess (METADATA Object){String} App_Short_Code Application short code.
 * @apiSuccess (METADATA Object){String} App_Title Application title.
 * @apiSuccess (METADATA Object){String} App_Title_iPhone Application title for iPhone.
 * @apiSuccess (METADATA Object){String} Description Application Description.
 * @apiSuccess (METADATA Object){String} Society_Facebook_URL Application URL for Facebook.
 * @apiSuccess (METADATA Object){String} Society_Twitter_URL Application URL for Twitter.
 * @apiSuccess (METADATA Object){String} Dart_ID Dart-id for the Application.
 * @apiSuccess (METADATA Object){String} Flurry_ID Flurry-id for the Application.
 * @apiSuccess (METADATA Object){String} Google_Analytics_Code Google Analytics code for the Application.
 * @apiSuccess (METADATA Object){String} ADMobNavKeyIphone AddMob key for the iPhone Application.
 * @apiSuccess (METADATA Object){String} ADMobNavKeyIpad AddMob key for the iPad  Application.
 * @apiSuccess (METADATA Object){String} ADMobDownloadKeyIphone AddMob download key for iPhone  
 * @apiSuccess (METADATA Object){String} ADMobDownloadKeyIpad AddMob download key for iPad.
 * @apiSuccess (METADATA Object){String} ADMobFullPagePortraitKeyIphone AddMob full page key for iPhone  
 * @apiSuccess (METADATA Object){String} ADMobFullPagePortraitKeyIpad AddMob full page key for the iPad  Application.
 * @apiSuccess (METADATA Object){String} ADMobFullPageLandscapeKeyIphone AddMob full page landscape key for the iPhone  Application.
 * @apiSuccess (METADATA Object){String} ADMobFullPageLandscapeKeyIpad AddMob full page landscape key for the iPad  Application.
 * @apiSuccess (METADATA Object){String} ADMobHomeKeyIphone AddMob home key for iPhone.
 * @apiSuccess (METADATA Object){String} ADMobHomeKeyIpad AddMob home key for iPad.
 * @apiSuccess (METADATA Object){String} ADMobTOCKeyIpad AddMob TOC key for iPad.
 * @apiSuccess (METADATA Object){String} ADMobTOCKeyIphone AddMob TOC key for iPhone.
 * @apiSuccess (METADATA Object){String} ADMobSkyScrapperIphone AddMob sky scrapper key for iPhone.
 * @apiSuccess (METADATA Object){String} ADMobSkyScrapperIpad AddMob sky scrapper key for iPad.
 * @apiSuccess (METADATA Object){String} Update_Link_Title Title for the Application update.
 * @apiSuccess (METADATA Object){String} Update_Link_Description Description for the Application update.
 * @apiSuccess (METADATA Object){String} Update_Link_URL URL for the Application update.
 * @apiSuccess (METADATA Object){Number} Update_Version  Updated Application version number.
 * @apiSuccess (METADATA Object){Date}   Last_Modified  Last modified time.
 * @apiSuccess (METADATA Object){String} s3_base_url URL for the S3 server.
 * @apiSuccess (METADATA Object){String} Update_Link_URL URL for the Application update.
 * @apiSuccess (METADATA Object){String} Update_Link_URL URL for the Application update.
 * @apiSuccess (METADATA Object){Object[]} JOURNALS Array of JOURNAL Objects.
 * @apiSuccess (METADATA Object){Object[]} SOCIETY_LINKS Array of SOCIETY_LINK Objects.


 * @apiSuccess (JOURNAL Object){Number} Journal_ID Journal ID for the Journal.
 * @apiSuccess (JOURNAL Object){Number} ISSN ISSN number for the Journal.
 * @apiSuccess (JOURNAL Object){String} Journal_Title Title for the Journal.
 * @apiSuccess (JOURNAL Object){String} Journal_Title_iPhone Title for the Journal in iPhone.
 * @apiSuccess (JOURNAL Object){Number} Journals_Short_Code Journal short code.
 * @apiSuccess (JOURNAL Object){String} Journal_Description Journal Description.
 * @apiSuccess (JOURNAL Object){String} Access_Type Access type for the Journal.
 * @apiSuccess (JOURNAL Object){String} Society_Login_Type Login type for the Journal.
 * @apiSuccess (JOURNAL Object){String} Journal_Facebook_URL Facebook URL for the Journal.
 * @apiSuccess (JOURNAL Object){String} Journal_Twitter_URL Twitter URL for the Journal.
 * @apiSuccess (JOURNAL Object){Number} Facebook_ID Facebook ID for the Journal.
 * @apiSuccess (JOURNAL Object){String} Twitter_kOAuthConsumerSecret Twitter secret key.
 * @apiSuccess (JOURNAL Object){String} Twitter_kOAuthConsumerKey Twitter consumer key.
 * @apiSuccess (JOURNAL Object){Number} Subscription_ID Subscription-ID for the Journal.
 * @apiSuccess (JOURNAL Object){String} Subscription_Price Subscription price for the Journal.
 * @apiSuccess (JOURNAL Object){String} Base_Content_URL Path for contents for the Journal.
 * @apiSuccess (JOURNAL Object){String} Cover_Image_Path Image path for the cover image for the Journal.
 * @apiSuccess (JOURNAL Object){String} AIP_Title Path Title for the Article in Press.
 * @apiSuccess (JOURNAL Object){String} AIP_Description Description for the Article in Press.
 * @apiSuccess (JOURNAL Object){String} branding_image_ipad_landscape Branding image name for Journal in iPad in Landscape Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_ipad_landscape_retina Branding retina-image name for Journal in iPad in Landscape Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_ipad_portrait Branding image name for Journal in iPad in Portrait Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_ipad_portrait_retina Branding retina-image name for Journal in iPad in Portrait Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_iphone_landscape Branding image name for Journal in iPhone in Landscape Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_iphone_landscape_retina Branding retina-image name for Journal in iPhone in Landscape Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_iphone_portrait Branding image name for Journal in iPhone in Portrait Mode.
 * @apiSuccess (JOURNAL Object){String} branding_image_iphone_portrait_retina Branding retina-image name for Journal in iPhone in Potrait Mode.
 * @apiSuccess (JOURNAL Object){Object[]} JOURNAL_LINKS Array of JOURNAL_LINK Objects.
 

 * @apiSuccess (JOURNAL_LINK Object){String} Journal_Link_Title Title for the Journal Link.
 * @apiSuccess (JOURNAL_LINK Object){String} Journal_Link_URL URL for the Journal Link.


 * @apiSuccess (SOCIETY_LINK Object){String} Society_Link_Title Title for the Society Link.
 * @apiSuccess (SOCIETY_LINK Object){String} Society_Link_URL URL for the Society Link.
 *
 * @apiSuccessExample Sample Success-Response:
 * {
 *   "date": "2013-08-19 12:34:22",
 *   "MESSAGE": "Data Found",
 *   "STATUS": "1",
 *   "METADATA": {
 *       "App_ID": "7",
 *       "App_Short_Code": "V40FNS",
 *       "App_Title": "Fertility Sterility",
 *       "App_Title_iPhone": "Fertility Sterility",
 *       "Description": "Fertility and Sterility",
 *       "Society_Facebook_URL": "",
 *       "Society_Twitter_URL": "",
 *       "Dart_ID": "",
 *       "Flurry_ID": "",
 *       "Google_Analytics_Code": "",
 *       "ADMobNavKeyIphone": "",
 *       "ADMobNavKeyIpad": "",
 *       "ADMobDownloadKeyIphone": "",
 *       "ADMobDownloadKeyIpad": "",
 *       "ADMobFullPagePortraitKeyIphone": "",
 *       "ADMobFullPagePortraitKeyIpad": "",
 *       "ADMobFullPageLandscapeKeyIphone": "",
 *       "ADMobFullPageLandscapeKeyIpad": "",
 *       "ADMobHomeKeyIphone": "",
 *       "ADMobHomeKeyIpad": "",
 *       "ADMobTOCKeyIpad": "",
 *       "ADMobTOCKeyIphone": "",
 *       "ADMobSkyScrapperIphone": "",
 *       "ADMobSkyScrapperIpad": "",
 *       "Update_Link_Title": "",
 *       "Update_Link_Description": "",
 *       "Update_Link_URL": "",
 *       "Update_Version": "4.0.1",
 *       "Last_Modified": "2013-08-13 20:09:19",
 *       "s3_base_url": "",
 *       "JOURNALS": [
 *           {
 *               "Journal_ID": "21",
 *               "ISSN": "00150282",
 *               "Journal_Title": "Fertility and Sterility",
 *               "Journal_Title_iPhone": "Fertility and Sterility",
 *               "Journals_Short_Code": "V40FNS",
 *               "Journal_Description": "Fertility and Sterility",
 *               "Access_Type": "Free Abstract",
 *               "Society_Login_Type": "HA",
 *               "Journal_Facebook_URL": "",
 *               "Journal_Twitter_URL": "",
 *               "Facebook_ID": "",
 *               "Twitter_kOAuthConsumerSecret": "",
 *               "Twitter_kOAuthConsumerKey": "",
 *               "Subscription_ID": "",
 *               "Subscription_Price": "",
 *               "Base_Content_URL": "https://s3.amazonaws.com/kiwi-puppet/40/00150282/files/",
 *               "Cover_Image_Path": "CoverImage2013-08-14_13_29_45FNS_150x200.png",
 *               "AIP_Title": "",
 *               "AIP_Description": "",
 *               "Last_Modified": "2013-08-14 13:29:45",
 *               "branding_image_ipad_landscape": "Journal_branding_graphic_ipad_L.png",
 *               "branding_image_ipad_landscape_retina": "Journal_branding_graphic_ipad_L@2x.png",
 *               "branding_image_ipad_portrait": "Journal_branding_graphic_ipad_P.png",
 *               "branding_image_ipad_portrait_retina": "Journal_branding_graphic_ipad_P@2x.png",
 *               "branding_image_iphone_landscape": null,
 *               "branding_image_iphone_landscape_retina": null,
 *               "branding_image_iphone_portrait": null,
 *               "branding_image_iphone_portrait_retina": null,
 *               "JOURNAL_LINKS": [
 *                   {
 *                       "Journal_Link_Title": "Test URL",
 *                       "Journal_Link_URL": "http://www.google.com"
 *                   }
 *               ]
 *           }
 *       ],
 *       "SOCIETY_LINKS": [
 *           {
 *               "Society_Link_Title": "App test url",
 *               "Society_Link_URL": "http://www.google.com"
 *           }
 *       ]
 *   }
 * }
 *
 * @apiError {Date} date Server current timestamp.
 * @apiError {String} MESSAGE Error Message.
 * @apiError {Number} STATUS Error Status Code.
 *
 * @apiErrorExample Sample Error-Response:
 * {
 *	 "date": "2013-08-19 11:39:00",
 *	 "MESSAGE": "No Data Found. App id is either empty or wrong.",
 *	 "STATUS": "0"
 * }   
 */