define({ api: [
  {
    "type": "get",
    "url": "/webservice/index.php/app2/index",
    "title": "All AIP",
    "name": "All_AIP",
    "version": "0.1.0",
    "group": "Mobile_Application_API",
    "description": "API will return all the Articles in Press for the specific App-ID & Journal.",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "type": "String",
            "field": "appid",
            "optional": false,
            "description": "Application ID generated by Jat 4.0."
          },
          {
            "group": "Parameter",
            "type": "Number",
            "field": "jid",
            "optional": false,
            "description": "Journal ID."
          },
          {
            "group": "Parameter",
            "type": "String",
            "field": "urlcode",
            "optional": false,
            "description": "Must equal \"aip\"."
          }
        ]
      }
    },
    "success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Success 200",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Status for the response."
          },
          {
            "group": "Success 200",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Status message for the response."
          },
          {
            "group": "Success 200",
            "type": "Object[]",
            "field": "ARTICLES",
            "optional": false,
            "description": "Array of ARTICLE Objects."
          }
        ],
        "ARTICLE Object": [
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "article_id",
            "optional": false,
            "description": "Article ID."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_title",
            "optional": false,
            "description": "Article Title."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "authors",
            "optional": false,
            "description": "Author of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "html_file_name",
            "optional": false,
            "description": "HTML file name of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "abstract",
            "optional": false,
            "description": "Abstract of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Date",
            "field": "date_of_release",
            "optional": false,
            "description": "Date of release of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_sub_type",
            "optional": false,
            "description": "Article Sub Type."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_type",
            "optional": false,
            "description": "Article Type."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "pdf_file_name",
            "optional": false,
            "description": "PDF file name for Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "keywords",
            "optional": false,
            "description": "Keywords for the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "isArticleInPress",
            "optional": false,
            "description": "Defines whether Article is in Press."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "page_range",
            "optional": false,
            "description": "Page range of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Date",
            "field": "last_modify",
            "optional": false,
            "description": "Last modified time of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_info_id",
            "optional": false,
            "description": "Article info number."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "Sequence",
            "optional": false,
            "description": "Sequence number for the Article in Press."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "DOI",
            "optional": false,
            "description": "Date of issue of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "DOI_Link",
            "optional": false,
            "description": "Link for date of issue of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "Video",
            "optional": false,
            "description": "Video of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "version",
            "optional": false,
            "description": "Version number of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "v40",
            "optional": false,
            "description": "Processsing 2.x, 3.x, 4.x."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "is_supplement",
            "optional": false,
            "description": "Defines whether Article is supplement."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "is_abstract",
            "optional": false,
            "description": "Defines whether Article has abstract."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "citation_text",
            "optional": false,
            "description": "Citation HTML text string."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_fulltext",
            "optional": false,
            "description": "Size of full text."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_abstract",
            "optional": false,
            "description": "Size of abstract text."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_pdf",
            "optional": false,
            "description": "Size of pdf."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_suppl",
            "optional": false,
            "description": "Size of supplement."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "copyright",
            "optional": false,
            "description": "Copyright for the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_video",
            "optional": false,
            "description": "Defines whether Article has video."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_audio",
            "optional": false,
            "description": "Defines whether Article has audio."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_image",
            "optional": false,
            "description": "Defines whether Article has image."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_others",
            "optional": false,
            "description": "Defines whether Article has other content."
          },
          {
            "group": "ARTICLE Object",
            "type": "Object[]",
            "field": "AUTHORS",
            "optional": false,
            "description": "Array of AUTHOR Objects."
          },
          {
            "group": "ARTICLE Object",
            "type": "Object[]",
            "field": "REFERENCES",
            "optional": false,
            "description": "Array of REFERENCE Objects."
          },
          {
            "group": "ARTICLE Object",
            "type": "Object[]",
            "field": "ARTICLE_MEDIAS",
            "optional": false,
            "description": "Array of ARTICLE_MEDIA Objects."
          }
        ],
        "AUTHOR Object": [
          {
            "group": "AUTHOR Object",
            "type": "Number",
            "field": "author_id",
            "optional": false,
            "description": "Author ID."
          },
          {
            "group": "AUTHOR Object",
            "type": "String",
            "field": "author_name",
            "optional": false,
            "description": "Author Name."
          },
          {
            "group": "AUTHOR Object",
            "type": "String",
            "field": "author_description",
            "optional": false,
            "description": "Author Description."
          },
          {
            "group": "AUTHOR Object",
            "type": "Date",
            "field": "last_modified",
            "optional": false,
            "description": "Last modified time."
          }
        ],
        "REFERENCE Object": [
          {
            "group": "REFERENCE Object",
            "type": "Number",
            "field": "reference_id",
            "optional": false,
            "description": "Reference ID."
          },
          {
            "group": "REFERENCE Object",
            "type": "String",
            "field": "section_id",
            "optional": false,
            "description": "Section ID."
          },
          {
            "group": "REFERENCE Object",
            "type": "String",
            "field": "section_title",
            "optional": false,
            "description": "Section title."
          },
          {
            "group": "REFERENCE Object",
            "type": "Boolean",
            "field": "is_this_sub_section",
            "optional": false,
            "description": "Defines whether it is a sub-section."
          },
          {
            "group": "REFERENCE Object",
            "type": "Date",
            "field": "last_modified",
            "optional": false,
            "description": "Last modified time."
          }
        ],
        "ARTICLE_MEDIA Object": [
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_type",
            "optional": false,
            "description": "Defines the Media Type."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_thumb_image_name",
            "optional": false,
            "description": "Media image name."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_file_name",
            "optional": false,
            "description": "Media file name."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_text",
            "optional": false,
            "description": "Media description."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_caption",
            "optional": false,
            "description": "Media caption."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "Boolean",
            "field": "deleted",
            "optional": false,
            "description": "Defines whether it is deleted."
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "{\n  \"date\": \"2013-08-19 12:36:58\",\n  \"STATUS\": \"1\",\n  \"MESSAGE\": \"Data Found\",\n  \"ARTICLES\": [\n      {\n         \"article_id\": \"1\",\n         \"issue_id\": \"0\",\n         \"article_title\": \"Pregnancies and deliveries per fresh cycle are no longer adequate indicators of in vitro fertilization program quality: how should registries adapt?\",\n         \"authors\": \"David R. Meldrum M.D.\",\n         \"html_file_name\": \"main.html\",\n         \"abstract\": \"\",\n         \"date_of_release\": \"2013-08-03\",\n         \"article_sub_type\": \"\",\n         \"article_type\": \"\",\n         \"pdf_file_name\": \"main.pdf\",\n         \"keywords\": \"\",\n         \"isArticleInPress\": \"1\",\n         \"page_range\": \"\",\n         \"last_modify\": \"2013-08-06 14:54:23\",\n         \"article_info_id\": \"S0015028213027489\",\n         \"Sequence\": \"0\",\n         \"DOI\": \"10.1016/j.fertnstert.2013.07.1969\",\n         \"DOI_Link\": \"http://dx.doi.org/10.1016/j.fertnstert.2013.07.1969\",\n         \"Video\": \"0\",\n         \"version\": null,\n         \"v40\": \"4\",\n         \"is_supplement\": \"0\",\n         \"is_abstract\": \"0\",\n         \"citation_text\": \"</head>Article Title Pregnancies and deliveries per fresh cycle are no longer adequate indicators of in vitro fertilization program quality: how should registries adapt?\\n Authors David R. Meldrum M.D. Source Fertility and Sterility - Aug 2013 DOI: 10.1016/j.fertnstert.2013.07.1969 </body></html>\",\n         \"filesize_fulltext\": \"6135\",\n         \"filesize_abstract\": \"0\",\n         \"filesize_pdf\": \"77961\",\n         \"filesize_suppl\": \"0\",\n         \"copyright\": \"© 2013 American Society for Reproductive Medicine\",\n         \"doctopic_role\": \"\",\n         \"has_video\": 0,\n         \"has_audio\": 0,\n         \"has_image\": 0,\n         \"has_others\": 0,\n         \"AUTHORS\": [\n             {\n                 \"author_id\": \"1\",\n                 \"author_name\": \"David R. Meldrum M.D.\",\n                 \"author_description\": \"Reproductive Partners Medical Group, Redondo Beach, California\",\n                 \"last_modified\": \"2013-08-06 14:54:23\"\n             }\n         ],\n         \"REFERENCES\": [\n             {\n                 \"reference_id\": \"1\",\n                 \"section_id\": \"xbib5\",\n                 \"section_title\": \"References\",\n                 \"is_this_sub_section\": \"1\",\n                 \"last_modified\": \"2013-08-06 14:54:22\"\n             }\n         ],\n         \"ARTICLE_MEDIAS\": [\n             {\n                 \"media_type\": \"Image\",\n                 \"media_thumb_image_name\": \"gr1.jpg\",\n                 \"media_file_name\": \"gr1.jpg\",\n                 \"media_text\": \"\",\n                 \"media_caption\": \"Figure 1</b> Replica of Sigmund Freud's couch, where patients presenting with endometriosis-like symptoms were often diagnosed with hysteria.</b>\",\n                 \"deleted\": \"0\"\n             },\n             {\n                 \"media_type\": \"Image\",\n                 \"media_thumb_image_name\": \"gr2.jpg\",\n                 \"media_file_name\": \"gr2.jpg\",\n                 \"media_text\": \" \",\n                 \"media_caption\": \"Figure 2</b> Experts on medieval medicine describe this late 13th-century image from a medical textbook as one depicting a case of uterine suffocation, a disease profile with many similarities to endometriosis.</b>\",\n                 \"deleted\": \"0\"\n             },\n             {\n                 \"media_type\": \"Image\",\n                 \"media_thumb_image_name\": \"gr3.jpg\",\n                 \"media_file_name\": \"gr3.jpg\",\n                 \"media_text\": \"\",\n                 \"media_caption\": \"Figure 3</b> In the Hippocratic Corpus several gynecological symptoms are mentioned, which bear striking similarity to those of endometriosis, including uterine ulcers, adhesions, and infertility.</b>\",\n                 \"deleted\": \"0\"\n             }\n         ]\n     }\n ]\n}\n"
        }
      ]
    },
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Error 4xx",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Error Message."
          },
          {
            "group": "Error 4xx",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Error Status Code."
          }
        ]
      },
      "examples": [
        {
          "title": "Error-Response:",
          "content": "{\n \"date\": \"2013-08-19 11:39:00\",\n \"MESSAGE\": \"No Data Found. Journal id or Application id is either empty or wrong.\",\n \"STATUS\": \"0\"\n}\n"
        }
      ]
    },
    "filename": "./AllAIP.js"
  },
  {
    "type": "get",
    "url": "webservice/index.php/app2/index",
    "title": "All Article",
    "name": "All_Article_for_an_Issue",
    "version": "0.1.0",
    "group": "Mobile_Application_API",
    "description": "API will return all the Articles for the specific App-ID, Journal & Issue.",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "type": "String",
            "field": "appid",
            "optional": false,
            "description": "Application ID generated by Jat 4.0."
          },
          {
            "group": "Parameter",
            "type": "Number",
            "field": "jid",
            "optional": false,
            "description": "Journal ID."
          },
          {
            "group": "Parameter",
            "type": "String",
            "field": "urlcode",
            "optional": false,
            "description": "Must equal \"issues\"."
          },
          {
            "group": "Parameter",
            "type": "String",
            "field": "issues",
            "optional": false,
            "description": "Comma separated Issue Numbers. Example: \"1,2\"."
          }
        ]
      }
    },
    "success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Success 200",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Status for the response."
          },
          {
            "group": "Success 200",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Status message for the response."
          },
          {
            "group": "Success 200",
            "type": "Object[]",
            "field": "ISSUES",
            "optional": false,
            "description": "Array of ISSUE Objects."
          }
        ],
        "ISSUE Object": [
          {
            "group": "ISSUE Object",
            "type": "Number",
            "field": "issue_id",
            "optional": false,
            "description": "Issue ID."
          },
          {
            "group": "ISSUE Object",
            "type": "Object[]",
            "field": "ARTICLES",
            "optional": false,
            "description": "Array of ARTICLE Objects."
          }
        ],
        "ARTICLE Object": [
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "article_id",
            "optional": false,
            "description": "Article ID."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_title",
            "optional": false,
            "description": "Article Title."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "authors",
            "optional": false,
            "description": "Author of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "html_file_name",
            "optional": false,
            "description": "HTML file name of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "abstract",
            "optional": false,
            "description": "Abstract of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Date",
            "field": "date_of_release",
            "optional": false,
            "description": "Date of release of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_sub_type",
            "optional": false,
            "description": "Article Sub Type."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_type",
            "optional": false,
            "description": "Article Type."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "pdf_file_name",
            "optional": false,
            "description": "PDF file name for Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "keywords",
            "optional": false,
            "description": "Keywords for the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "isArticleInPress",
            "optional": false,
            "description": "Defines whether Article is in Press."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "page_range",
            "optional": false,
            "description": "Page range of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Date",
            "field": "last_modify",
            "optional": false,
            "description": "Last modified time of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "article_info_id",
            "optional": false,
            "description": "Article info number."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "Sequence",
            "optional": false,
            "description": "Sequence number for the Article in Press."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "DOI",
            "optional": false,
            "description": "Date of issue of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "DOI_Link",
            "optional": false,
            "description": "Link for date of issue of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "Video",
            "optional": false,
            "description": "Video of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "version",
            "optional": false,
            "description": "Version number of the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "v40",
            "optional": false,
            "description": "Processsing 2.x, 3.x, 4.x."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "is_supplement",
            "optional": false,
            "description": "Defines whether Article is supplement."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "is_abstract",
            "optional": false,
            "description": "Defines whether Article has abstract."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "citation_text",
            "optional": false,
            "description": "Citation HTML text string."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_fulltext",
            "optional": false,
            "description": "Size of full text."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_abstract",
            "optional": false,
            "description": "Size of abstract text."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_pdf",
            "optional": false,
            "description": "Size of pdf."
          },
          {
            "group": "ARTICLE Object",
            "type": "Number",
            "field": "filesize_suppl",
            "optional": false,
            "description": "Size of supplement."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "copyright",
            "optional": false,
            "description": "Copyright for the Article."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_video",
            "optional": false,
            "description": "Defines whether Article has video."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_audio",
            "optional": false,
            "description": "Defines whether Article has audio."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_image",
            "optional": false,
            "description": "Defines whether Article has image."
          },
          {
            "group": "ARTICLE Object",
            "type": "Boolean",
            "field": "has_others",
            "optional": false,
            "description": "Defines whether Article has other content."
          },
          {
            "group": "ARTICLE Object",
            "type": "String",
            "field": "Issue_PII",
            "optional": false,
            "description": "Issue PII Number."
          },
          {
            "group": "ARTICLE Object",
            "type": "Object[]",
            "field": "AUTHORS",
            "optional": false,
            "description": "Array of AUTHOR Objects."
          },
          {
            "group": "ARTICLE Object",
            "type": "Object[]",
            "field": "REFERENCES",
            "optional": false,
            "description": "Array of REFERENCE Objects."
          },
          {
            "group": "ARTICLE Object",
            "type": "Object[]",
            "field": "ARTICLE_MEDIAS",
            "optional": false,
            "description": "Array of ARTICLE_MEDIA Objects."
          }
        ],
        "AUTHOR Object": [
          {
            "group": "AUTHOR Object",
            "type": "Number",
            "field": "author_id",
            "optional": false,
            "description": "Author ID."
          },
          {
            "group": "AUTHOR Object",
            "type": "String",
            "field": "author_name",
            "optional": false,
            "description": "Author Name."
          },
          {
            "group": "AUTHOR Object",
            "type": "String",
            "field": "author_description",
            "optional": false,
            "description": "Author Description."
          },
          {
            "group": "AUTHOR Object",
            "type": "Date",
            "field": "last_modified",
            "optional": false,
            "description": "Last modified time."
          }
        ],
        "REFERENCE Object": [
          {
            "group": "REFERENCE Object",
            "type": "Number",
            "field": "reference_id",
            "optional": false,
            "description": "Reference ID."
          },
          {
            "group": "REFERENCE Object",
            "type": "String",
            "field": "section_id",
            "optional": false,
            "description": "Section ID."
          },
          {
            "group": "REFERENCE Object",
            "type": "String",
            "field": "section_title",
            "optional": false,
            "description": "Section title."
          },
          {
            "group": "REFERENCE Object",
            "type": "Boolean",
            "field": "is_this_sub_section",
            "optional": false,
            "description": "Defines whether it is a sub-section."
          },
          {
            "group": "REFERENCE Object",
            "type": "Date",
            "field": "last_modified",
            "optional": false,
            "description": "Last modified time."
          }
        ],
        "ARTICLE_MEDIA Object": [
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_type",
            "optional": false,
            "description": "Defines the Media Type."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_thumb_image_name",
            "optional": false,
            "description": "Media image name."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_file_name",
            "optional": false,
            "description": "Media file name."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_text",
            "optional": false,
            "description": "Media description."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "String",
            "field": "media_caption",
            "optional": false,
            "description": "Media caption."
          },
          {
            "group": "ARTICLE_MEDIA Object",
            "type": "Boolean",
            "field": "deleted",
            "optional": false,
            "description": "Defines whether it is deleted."
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "{\n \"date\": \"2013-08-19 12:38:39\",\n \"STATUS\": \"1\",\n \"MESSAGE\": \"Data Found\",\n \"ISSUES\": [\n     {\n         \"issue_id\": \"1\",\n         \"ARTICLES\": [\n             {\n                 \"article_id\": \"5\",\n                 \"issue_id\": \"1\",\n                 \"article_title\": \"Endometriosis: ancient disease, ancient treatments\",\n                 \"authors\": \"Camran Nezhat M.D., Farr Nezhat M.D., Ceana Nezhat M.D.\",\n                 \"html_file_name\": \"main.html\",\n                 \"abstract\": \"\",\n                 \"date_of_release\": \"2012-12-01\",\n                 \"article_sub_type\": \"\",\n                 \"article_type\": \"\",\n                 \"pdf_file_name\": \"main.pdf\",\n                 \"keywords\": \"\",\n                 \"isArticleInPress\": \"0\",\n                 \"page_range\": \"S1-S62\",\n                 \"last_modify\": \"2013-08-06 19:11:16\",\n                 \"article_info_id\": \"S0015028212019553\",\n                 \"Sequence\": \"1\",\n                 \"DOI\": \"10.1016/j.fertnstert.2012.08.001\",\n                 \"DOI_Link\": \"http://dx.doi.org/10.1016/j.fertnstert.2012.08.001\",\n                 \"Video\": \"0\",\n                 \"version\": null,\n                 \"v40\": \"4\",\n                 \"is_supplement\": \"0\",\n                 \"is_abstract\": \"0\",\n                 \"citation_text\": \"\\n</head>\\n Article Title\\n \\n Endometriosis: ancient disease, ancient treatments\\n Authors \\n \\n Camran Nezhat M.D., Farr Nezhat M.D., Ceana Nezhat M.D.\\n Source \\n \\n Fertility and Sterility - Dec 2012 \\n Vol 98 | Issue 6, Supplement | Pages S1-S62 \\n DOI: 10.1016/j.fertnstert.2012.08.001\\n \\n</body>\\n</html>\",\n                 \"filesize_fulltext\": \"28841854\",\n                 \"filesize_abstract\": \"0\",\n                 \"filesize_pdf\": \"14368998\",\n                 \"filesize_suppl\": \"0\",\n                 \"copyright\": \"© 2012 American Society for Reproductive Medicine\",\n                 \"doctopic_role\": \"\",\n                 \"Issue_PII\": \"S0161642013X00089\",\n                 \"has_video\": 0,\n                 \"has_audio\": 0,\n                 \"has_image\": 1,\n                 \"has_others\": 0,\n                 \"AUTHORS\": [\n                     {\n                         \"author_id\": \"16\",\n                         \"author_name\": \"Camran Nezhat M.D.\",\n                         \"author_description\": \" Stanford University Medical Center, Palo Alto, California Reprint requests: Camran Nezhat, M.D., 900 Welch Road, Suite 403, Palo Alto, California 94304. Email Address :cnezhat@stanford.edu\",\n                         \"last_modified\": \"2013-08-06 14:57:34\"\n                     },\n                     {\n                         \"author_id\": \"17\",\n                         \"author_name\": \"Farr Nezhat M.D.\",\n                         \"author_description\": \" Columbia University, New York, New York St. Luke's-Roosevelt's Hospital, New York, New York\",\n                         \"last_modified\": \"2013-08-06 14:57:34\"\n                     },\n                     {\n                         \"author_id\": \"18\",\n                         \"author_name\": \"Ceana Nezhat M.D.\",\n                         \"author_description\": \" Stanford University Medical Center, Palo Alto, California Northside Hospital, Atlanta, Georgia\",\n                         \"last_modified\": \"2013-08-06 14:57:34\"\n                     }\n                 ],\n                 \"REFERENCES\": [\n                     {\n                         \"reference_id\": \"9\",\n                         \"section_id\": \"xbib219\",\n                         \"section_title\": \"References\",\n                         \"is_this_sub_section\": \"1\",\n                         \"last_modified\": \"2013-08-06 14:55:05\"\n                     }\n                 ],\n                 \"ARTICLE_MEDIAS\": [\n                     {\n                         \"media_type\": \"Image\",\n                         \"media_thumb_image_name\": \"gr1.jpg\",\n                         \"media_file_name\": \"gr1.jpg\",\n                         \"media_text\": \"\",\n                         \"media_caption\": \"Figure 1</b> Replica of Sigmund Freud's couch, where patients presenting with endometriosis-like symptoms were often diagnosed with hysteria.</b>\",\n                         \"deleted\": \"0\"\n                     },\n                     {\n                         \"media_type\": \"Image\",\n                         \"media_thumb_image_name\": \"gr2.jpg\",\n                         \"media_file_name\": \"gr2.jpg\",\n                         \"media_text\": \"\",\n                         \"media_caption\": \"Figure 2</b> Experts on medieval medicine describe this late 13th-century image from a medical textbook as one depicting a case of uterine suffocation, a disease profile with many similarities to endometriosis.</b>\",\n                         \"deleted\": \"0\"\n                     },\n                     {\n                         \"media_type\": \"Image\",\n                         \"media_thumb_image_name\": \"gr3.jpg\",\n                         \"media_file_name\": \"gr3.jpg\",\n                         \"media_text\": \"\",\n                         \"media_caption\": \"Figure 3</b> In the Hippocratic Corpus several gynecological symptoms are mentioned, which bear striking similarity to those of endometriosis, including uterine ulcers, adhesions, and infertility.</b>\",\n                         \"deleted\": \"0\"\n                     }\n                 ]\n             }\n         ]\n     }\n ]\n}\n"
        }
      ]
    },
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Error 4xx",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Error Message."
          },
          {
            "group": "Error 4xx",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Error Status Code."
          }
        ]
      },
      "examples": [
        {
          "title": "Error-Response:",
          "content": "{\n \"date\": \"2013-08-19 11:39:00\",\n \"MESSAGE\": \"No Data Found. Issue id is either empty or wrong.\",\n \"STATUS\": \"0\"\n}\n"
        }
      ]
    },
    "filename": "./AllArticles.js"
  },
  {
    "type": "get",
    "url": "/webservice/index.php/app2/index",
    "title": "All Issues",
    "name": "All_Issues",
    "version": "0.1.0",
    "group": "Mobile_Application_API",
    "description": "API will return all the Issues for the specific App-ID & Journal",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "type": "String",
            "field": "appid",
            "optional": false,
            "description": "Application ID generated by Jat 4.0."
          },
          {
            "group": "Parameter",
            "type": "Number",
            "field": "jid",
            "optional": false,
            "description": "Journal ID."
          },
          {
            "group": "Parameter",
            "type": "String",
            "field": "urlcode",
            "optional": false,
            "description": "Must equal \"issues\"."
          }
        ]
      }
    },
    "success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Success 200",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Status for the response."
          },
          {
            "group": "Success 200",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Status message for the response."
          },
          {
            "group": "Success 200",
            "type": "Object[]",
            "field": "ISSUES",
            "optional": false,
            "description": "Array of ISSUE Objects."
          },
          {
            "group": "Success 200",
            "type": "Object[]",
            "field": "MEDIA_TYPE",
            "optional": false,
            "description": "Array of MEDIA_TYPE Objects."
          },
          {
            "group": "Success 200",
            "type": "Number",
            "field": "aip_badge",
            "optional": false,
            "description": "Article in Press badge number."
          }
        ],
        "ISSUE Object": [
          {
            "group": "ISSUE Object",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Last time data got updated."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Status message for the response."
          },
          {
            "group": "ISSUE Object",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Status for the response."
          },
          {
            "group": "ISSUE Object",
            "type": "Number",
            "field": "issue_id",
            "optional": false,
            "description": "Unique Issue id for the Journal."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "issue_number",
            "optional": false,
            "description": "Issue number for the Journal."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "issue_name",
            "optional": false,
            "description": "Issue Name."
          },
          {
            "group": "ISSUE Object",
            "type": "Number",
            "field": "volume",
            "optional": false,
            "description": "Volume number of the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "editors",
            "optional": false,
            "description": "Editors of the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "page_range",
            "optional": false,
            "description": "Page Range of the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "Date",
            "field": "last_modified",
            "optional": false,
            "description": "Last modified time."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "issue_title",
            "optional": false,
            "description": "Issue Title."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "special_editors",
            "optional": false,
            "description": "Special Editors of the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "special_Issue",
            "optional": false,
            "description": "Special Issue linked with the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "Video",
            "optional": false,
            "description": "Video URL for the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "Cover_Image",
            "optional": false,
            "description": "Cover Image path for the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "Product_ID",
            "optional": false,
            "description": "Product ID for the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "Price",
            "optional": false,
            "description": "Price for the Issue."
          },
          {
            "group": "ISSUE Object",
            "type": "String",
            "field": "Issue_PII",
            "optional": false,
            "description": "PII number for the Issue."
          }
        ],
        "MEDIA_TYPE Object": [
          {
            "group": "MEDIA_TYPE Object",
            "type": "Number",
            "field": "media_type_id",
            "optional": false,
            "description": "Defines the Media Type."
          },
          {
            "group": "MEDIA_TYPE Object",
            "type": "String",
            "field": "media_type",
            "optional": false,
            "description": "Defines the Media name."
          }
        ]
      },
      "examples": [
        {
          "title": "Success-Response:",
          "content": "{\n \"date\": \"2013-08-19 12:35:16\",\n \"STATUS\": \"1\",\n \"MESSAGE\": \"Data Found\",\n \"ISSUES\": [\n     {\n         \"issue_id\": \"1\",\n         \"issue_number\": \"6, Supplement\",\n         \"issue_name\": \"Endometriosis: ancient disease,ancient treatments\",\n         \"volume\": \"98\",\n         \"editors\": \"Camran Nezhat MD\",\n         \"date_of_release\": \"2012-12-01\",\n         \"page_range\": \"A1-A2, S1-S62\",\n         \"last_modified\": \"2013-08-06 14:55:00\",\n         \"issue_title\": \"Endometriosis: ancient disease,ancient treatments\",\n         \"special_editors\": \"Camran Nezhat MD\",\n         \"special_Issue\": \"\\u0001\",\n         \"Video\": \"\\u0000\",\n         \"Cover_Image\": \"1.jpg\",\n         \"Product_ID\": \"com.elsevier.gmr.jat.newsstand.fns.singleissue.S0015028212X00025\",\n         \"Price\": \"$31.99\",\n         \"Issue_PII\": \"S0161642013X00089\"\n     }\n ],\n \"MEDIA_TYPE\": [\n     {\n         \"media_type_id\": \"1\",\n         \"media_type\": \"Video\"\n     },\n     {\n         \"media_type_id\": \"2\",\n         \"media_type\": \"Audio\"\n     },\n     {\n         \"media_type_id\": \"3\",\n         \"media_type\": \"Document\"\n     },\n     {\n         \"media_type_id\": \"4\",\n         \"media_type\": \"Presentation\"\n     },\n     {\n         \"media_type_id\": \"5\",\n         \"media_type\": \"Spreadsheet\"\n     },\n     {\n         \"media_type_id\": \"6\",\n         \"media_type\": \"PDF\"\n     },\n     {\n         \"media_type_id\": \"7\",\n         \"media_type\": \"Image\"\n     },\n     {\n         \"media_type_id\": \"8\",\n         \"media_type\": \"Table\"\n     }\n ],\n \"aip_badge\": 0\n}\n"
        }
      ]
    },
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Error 4xx",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Error Message."
          },
          {
            "group": "Error 4xx",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Error Status Code."
          }
        ]
      },
      "examples": [
        {
          "title": "Error-Response:",
          "content": "{\n \"date\": \"2013-08-19 11:39:00\",\n \"MESSAGE\": \"No Data Found. Journal id is either empty or wrong.\",\n \"STATUS\": \"0\"\n}\n"
        }
      ]
    },
    "filename": "./AllIssues.js"
  },
  {
    "type": "get",
    "url": "webservice/index.php/app2/index",
    "title": "All Journals",
    "name": "All_Journals",
    "version": "0.1.0",
    "group": "Mobile_Application_API",
    "description": "API will return all the Journals for the specific App-ID",
    "parameter": {
      "fields": {
        "Parameter": [
          {
            "group": "Parameter",
            "type": "Number",
            "field": "appid",
            "optional": false,
            "description": "Application ID generated by Jat 4.0."
          }
        ]
      }
    },
    "success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "Date",
            "field": "Server",
            "optional": false,
            "description": "current timestamp."
          },
          {
            "group": "Success 200",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Status for the response."
          },
          {
            "group": "Success 200",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Status message for the response."
          },
          {
            "group": "Success 200",
            "type": "Object",
            "field": "METADATA",
            "optional": false,
            "description": "METADATA Object."
          }
        ],
        "METADATA Object": [
          {
            "group": "METADATA Object",
            "type": "Number",
            "field": "App_ID",
            "optional": false,
            "description": "Application ID."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "App_Short_Code",
            "optional": false,
            "description": "Application short code."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "App_Title",
            "optional": false,
            "description": "Application title."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "App_Title_iPhone",
            "optional": false,
            "description": "Application title for iPhone."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Description",
            "optional": false,
            "description": "Application Description."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Society_Facebook_URL",
            "optional": false,
            "description": "Application URL for Facebook."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Society_Twitter_URL",
            "optional": false,
            "description": "Application URL for Twitter."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Dart_ID",
            "optional": false,
            "description": "Dart-id for the Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Flurry_ID",
            "optional": false,
            "description": "Flurry-id for the Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Google_Analytics_Code",
            "optional": false,
            "description": "Google Analytics code for the Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobNavKeyIphone",
            "optional": false,
            "description": "AddMob key for the iPhone Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobNavKeyIpad",
            "optional": false,
            "description": "AddMob key for the iPad  Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobDownloadKeyIphone",
            "optional": false,
            "description": "AddMob download key for iPhone"
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobDownloadKeyIpad",
            "optional": false,
            "description": "AddMob download key for iPad."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobFullPagePortraitKeyIphone",
            "optional": false,
            "description": "AddMob full page key for iPhone"
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobFullPagePortraitKeyIpad",
            "optional": false,
            "description": "AddMob full page key for the iPad  Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobFullPageLandscapeKeyIphone",
            "optional": false,
            "description": "AddMob full page landscape key for the iPhone  Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobFullPageLandscapeKeyIpad",
            "optional": false,
            "description": "AddMob full page landscape key for the iPad  Application."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobHomeKeyIphone",
            "optional": false,
            "description": "AddMob home key for iPhone."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobHomeKeyIpad",
            "optional": false,
            "description": "AddMob home key for iPad."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobTOCKeyIpad",
            "optional": false,
            "description": "AddMob TOC key for iPad."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobTOCKeyIphone",
            "optional": false,
            "description": "AddMob TOC key for iPhone."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobSkyScrapperIphone",
            "optional": false,
            "description": "AddMob sky scrapper key for iPhone."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "ADMobSkyScrapperIpad",
            "optional": false,
            "description": "AddMob sky scrapper key for iPad."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Update_Link_Title",
            "optional": false,
            "description": "Title for the Application update."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Update_Link_Description",
            "optional": false,
            "description": "Description for the Application update."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "Update_Link_URL",
            "optional": false,
            "description": "URL for the Application update."
          },
          {
            "group": "METADATA Object",
            "type": "Number",
            "field": "Update_Version",
            "optional": false,
            "description": "Updated Application version number."
          },
          {
            "group": "METADATA Object",
            "type": "Date",
            "field": "Last_Modified",
            "optional": false,
            "description": "Last modified time."
          },
          {
            "group": "METADATA Object",
            "type": "String",
            "field": "s3_base_url",
            "optional": false,
            "description": "URL for the S3 server."
          },
          {
            "group": "METADATA Object",
            "type": "Object[]",
            "field": "JOURNALS",
            "optional": false,
            "description": "Array of JOURNAL Objects."
          },
          {
            "group": "METADATA Object",
            "type": "Object[]",
            "field": "SOCIETY_LINKS",
            "optional": false,
            "description": "Array of SOCIETY_LINK Objects."
          }
        ],
        "JOURNAL Object": [
          {
            "group": "JOURNAL Object",
            "type": "Number",
            "field": "Journal_ID",
            "optional": false,
            "description": "Journal ID for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "Number",
            "field": "ISSN",
            "optional": false,
            "description": "ISSN number for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Journal_Title",
            "optional": false,
            "description": "Title for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Journal_Title_iPhone",
            "optional": false,
            "description": "Title for the Journal in iPhone."
          },
          {
            "group": "JOURNAL Object",
            "type": "Number",
            "field": "Journals_Short_Code",
            "optional": false,
            "description": "Journal short code."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Journal_Description",
            "optional": false,
            "description": "Journal Description."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Access_Type",
            "optional": false,
            "description": "Access type for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Society_Login_Type",
            "optional": false,
            "description": "Login type for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Journal_Facebook_URL",
            "optional": false,
            "description": "Facebook URL for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Journal_Twitter_URL",
            "optional": false,
            "description": "Twitter URL for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "Number",
            "field": "Facebook_ID",
            "optional": false,
            "description": "Facebook ID for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Twitter_kOAuthConsumerSecret",
            "optional": false,
            "description": "Twitter secret key."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Twitter_kOAuthConsumerKey",
            "optional": false,
            "description": "Twitter consumer key."
          },
          {
            "group": "JOURNAL Object",
            "type": "Number",
            "field": "Subscription_ID",
            "optional": false,
            "description": "Subscription-ID for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Subscription_Price",
            "optional": false,
            "description": "Subscription price for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Base_Content_URL",
            "optional": false,
            "description": "Path for contents for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "Cover_Image_Path",
            "optional": false,
            "description": "Image path for the cover image for the Journal."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "AIP_Title",
            "optional": false,
            "description": "Path Title for the Article in Press."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "AIP_Description",
            "optional": false,
            "description": "Description for the Article in Press."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_ipad_landscape",
            "optional": false,
            "description": "Branding image name for Journal in iPad in Landscape Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_ipad_landscape_retina",
            "optional": false,
            "description": "Branding retina-image name for Journal in iPad in Landscape Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_ipad_portrait",
            "optional": false,
            "description": "Branding image name for Journal in iPad in Portrait Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_ipad_portrait_retina",
            "optional": false,
            "description": "Branding retina-image name for Journal in iPad in Portrait Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_iphone_landscape",
            "optional": false,
            "description": "Branding image name for Journal in iPhone in Landscape Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_iphone_landscape_retina",
            "optional": false,
            "description": "Branding retina-image name for Journal in iPhone in Landscape Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_iphone_portrait",
            "optional": false,
            "description": "Branding image name for Journal in iPhone in Portrait Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "String",
            "field": "branding_image_iphone_portrait_retina",
            "optional": false,
            "description": "Branding retina-image name for Journal in iPhone in Potrait Mode."
          },
          {
            "group": "JOURNAL Object",
            "type": "Object[]",
            "field": "JOURNAL_LINKS",
            "optional": false,
            "description": "Array of JOURNAL_LINK Objects."
          }
        ],
        "JOURNAL_LINK Object": [
          {
            "group": "JOURNAL_LINK Object",
            "type": "String",
            "field": "Journal_Link_Title",
            "optional": false,
            "description": "Title for the Journal Link."
          },
          {
            "group": "JOURNAL_LINK Object",
            "type": "String",
            "field": "Journal_Link_URL",
            "optional": false,
            "description": "URL for the Journal Link."
          }
        ],
        "SOCIETY_LINK Object": [
          {
            "group": "SOCIETY_LINK Object",
            "type": "String",
            "field": "Society_Link_Title",
            "optional": false,
            "description": "Title for the Society Link."
          },
          {
            "group": "SOCIETY_LINK Object",
            "type": "String",
            "field": "Society_Link_URL",
            "optional": false,
            "description": "URL for the Society Link."
          }
        ]
      },
      "examples": [
        {
          "title": "Sample Success-Response:",
          "content": "{\n \"date\": \"2013-08-19 12:34:22\",\n \"MESSAGE\": \"Data Found\",\n \"STATUS\": \"1\",\n \"METADATA\": {\n     \"App_ID\": \"7\",\n     \"App_Short_Code\": \"V40FNS\",\n     \"App_Title\": \"Fertility Sterility\",\n     \"App_Title_iPhone\": \"Fertility Sterility\",\n     \"Description\": \"Fertility and Sterility\",\n     \"Society_Facebook_URL\": \"\",\n     \"Society_Twitter_URL\": \"\",\n     \"Dart_ID\": \"\",\n     \"Flurry_ID\": \"\",\n     \"Google_Analytics_Code\": \"\",\n     \"ADMobNavKeyIphone\": \"\",\n     \"ADMobNavKeyIpad\": \"\",\n     \"ADMobDownloadKeyIphone\": \"\",\n     \"ADMobDownloadKeyIpad\": \"\",\n     \"ADMobFullPagePortraitKeyIphone\": \"\",\n     \"ADMobFullPagePortraitKeyIpad\": \"\",\n     \"ADMobFullPageLandscapeKeyIphone\": \"\",\n     \"ADMobFullPageLandscapeKeyIpad\": \"\",\n     \"ADMobHomeKeyIphone\": \"\",\n     \"ADMobHomeKeyIpad\": \"\",\n     \"ADMobTOCKeyIpad\": \"\",\n     \"ADMobTOCKeyIphone\": \"\",\n     \"ADMobSkyScrapperIphone\": \"\",\n     \"ADMobSkyScrapperIpad\": \"\",\n     \"Update_Link_Title\": \"\",\n     \"Update_Link_Description\": \"\",\n     \"Update_Link_URL\": \"\",\n     \"Update_Version\": \"4.0.1\",\n     \"Last_Modified\": \"2013-08-13 20:09:19\",\n     \"s3_base_url\": \"\",\n     \"JOURNALS\": [\n         {\n             \"Journal_ID\": \"21\",\n             \"ISSN\": \"00150282\",\n             \"Journal_Title\": \"Fertility and Sterility\",\n             \"Journal_Title_iPhone\": \"Fertility and Sterility\",\n             \"Journals_Short_Code\": \"V40FNS\",\n             \"Journal_Description\": \"Fertility and Sterility\",\n             \"Access_Type\": \"Free Abstract\",\n             \"Society_Login_Type\": \"HA\",\n             \"Journal_Facebook_URL\": \"\",\n             \"Journal_Twitter_URL\": \"\",\n             \"Facebook_ID\": \"\",\n             \"Twitter_kOAuthConsumerSecret\": \"\",\n             \"Twitter_kOAuthConsumerKey\": \"\",\n             \"Subscription_ID\": \"\",\n             \"Subscription_Price\": \"\",\n             \"Base_Content_URL\": \"https://s3.amazonaws.com/kiwi-puppet/40/00150282/files/\",\n             \"Cover_Image_Path\": \"CoverImage2013-08-14_13_29_45FNS_150x200.png\",\n             \"AIP_Title\": \"\",\n             \"AIP_Description\": \"\",\n             \"Last_Modified\": \"2013-08-14 13:29:45\",\n             \"branding_image_ipad_landscape\": \"Journal_branding_graphic_ipad_L.png\",\n             \"branding_image_ipad_landscape_retina\": \"Journal_branding_graphic_ipad_L@2x.png\",\n             \"branding_image_ipad_portrait\": \"Journal_branding_graphic_ipad_P.png\",\n             \"branding_image_ipad_portrait_retina\": \"Journal_branding_graphic_ipad_P@2x.png\",\n             \"branding_image_iphone_landscape\": null,\n             \"branding_image_iphone_landscape_retina\": null,\n             \"branding_image_iphone_portrait\": null,\n             \"branding_image_iphone_portrait_retina\": null,\n             \"JOURNAL_LINKS\": [\n                 {\n                     \"Journal_Link_Title\": \"Test URL\",\n                     \"Journal_Link_URL\": \"http://www.google.com\"\n                 }\n             ]\n         }\n     ],\n     \"SOCIETY_LINKS\": [\n         {\n             \"Society_Link_Title\": \"App test url\",\n             \"Society_Link_URL\": \"http://www.google.com\"\n         }\n     ]\n }\n}\n"
        }
      ]
    },
    "error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "type": "Date",
            "field": "date",
            "optional": false,
            "description": "Server current timestamp."
          },
          {
            "group": "Error 4xx",
            "type": "String",
            "field": "MESSAGE",
            "optional": false,
            "description": "Error Message."
          },
          {
            "group": "Error 4xx",
            "type": "Number",
            "field": "STATUS",
            "optional": false,
            "description": "Error Status Code."
          }
        ]
      },
      "examples": [
        {
          "title": "Sample Error-Response:",
          "content": "{\n \"date\": \"2013-08-19 11:39:00\",\n \"MESSAGE\": \"No Data Found. App id is either empty or wrong.\",\n \"STATUS\": \"0\"\n}\n"
        }
      ]
    },
    "filename": "./AllJournals.js"
  }
] });